// <auto-generated />
using System;
using FullstackProject.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FullstackProject.Model.Migrations
{
    [DbContext(typeof(S22024Group2ProjectContext))]
    [Migration("20260809112317_AddPurchasesAndPayments")]
    partial class AddPurchasesAndPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("FullstackProject.Model.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .HasColumnType("int")
                        .HasColumnName("DeveloperID");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("DeveloperId")
                        .HasName("PK__Develope__DE084CD149B01792");

                    b.HasIndex(new[] { "Email" }, "UQ__Develope__A9D10534268086DC")
                        .IsUnique();

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("FullstackProject.Model.Game", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("int")
                        .HasColumnName("DeveloperID");

                    b.Property<string>("DeveloperName")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IsAvailableOnMembership")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("GameId")
                        .HasName("PK__Games__2AB897DDDAE95024");

                    b.HasIndex(new[] { "DeveloperId" }, "IX_Games_DeveloperID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FullstackProject.Model.GameLibrary", b =>
                {
                    b.Property<int>("LibraryId")
                        .HasColumnType("int")
                        .HasColumnName("LibraryID");

                    b.Property<DateOnly?>("DateAdded")
                        .HasColumnType("date");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<decimal?>("PricePaid")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LibraryId")
                        .HasName("PK__GameLibr__A13647BF43F008E5");

                    b.HasIndex(new[] { "GameId" }, "IX_GameLibrary_GameID");

                    b.HasIndex(new[] { "UserId" }, "IX_GameLibrary_UserID");

                    b.ToTable("GameLibrary", (string)null);
                });

            modelBuilder.Entity("FullstackProject.Model.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .HasColumnType("int")
                        .HasColumnName("MembershipID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("DiscountRate")
                        .HasColumnType("float");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MembershipId")
                        .HasName("PK__Membersh__92A785990BEA4EC2");

                    b.HasIndex(new[] { "UserId" }, "UQ__Membersh__1788CCADDB5B030F")
                        .IsUnique()
                        .HasFilter("([UserID] IS NOT NULL)");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("FullstackProject.Model.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseID");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A5810BBE4EE");

                    b.HasIndex(new[] { "PurchaseId" }, "IX_Payments_PurchaseID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FullstackProject.Model.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseID");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<decimal?>("PricePaid")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PurchaseId")
                        .HasName("PK__Purchase__6B0A6BDE536E93D6");

                    b.HasIndex(new[] { "GameId" }, "IX_Purchases_GameID");

                    b.HasIndex(new[] { "UserId" }, "IX_Purchases_UserID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("FullstackProject.Model.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79AEB172D10E");

                    b.HasIndex(new[] { "GameId" }, "IX_Reviews_GameID");

                    b.HasIndex(new[] { "UserId" }, "IX_Reviews_UserID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FullstackProject.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A139672AF");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FullstackProject.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfileInfo")
                        .HasColumnType("text");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC0F3D84C5");

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleID");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105349FA7B6FF")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("FullstackProject.Model.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullstackProject.Model.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetRoleClaim", b =>
                {
                    b.HasOne("FullstackProject.Model.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetUserClaim", b =>
                {
                    b.HasOne("FullstackProject.Model.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetUserLogin", b =>
                {
                    b.HasOne("FullstackProject.Model.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetUserToken", b =>
                {
                    b.HasOne("FullstackProject.Model.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.Game", b =>
                {
                    b.HasOne("FullstackProject.Model.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .HasConstraintName("FK__Games__Developer__52593CB8");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("FullstackProject.Model.GameLibrary", b =>
                {
                    b.HasOne("FullstackProject.Model.Game", "Game")
                        .WithMany("GameLibraries")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__GameLibra__GameI__5629CD9C");

                    b.HasOne("FullstackProject.Model.User", "User")
                        .WithMany("GameLibraries")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__GameLibra__UserI__5535A963");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.Membership", b =>
                {
                    b.HasOne("FullstackProject.Model.User", "User")
                        .WithOne("Membership")
                        .HasForeignKey("FullstackProject.Model.Membership", "UserId")
                        .HasConstraintName("FK__Membershi__UserI__59FA5E80");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.Payment", b =>
                {
                    b.HasOne("FullstackProject.Model.Purchase", "Purchase")
                        .WithMany("Payments")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK__Payments__Purcha__656C112C");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("FullstackProject.Model.Purchase", b =>
                {
                    b.HasOne("FullstackProject.Model.Game", "Game")
                        .WithMany("Purchases")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__Purchases__GameI__628FA481");

                    b.HasOne("FullstackProject.Model.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Purchases__UserI__619B8048");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.Review", b =>
                {
                    b.HasOne("FullstackProject.Model.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__Reviews__GameID__5DCAEF64");

                    b.HasOne("FullstackProject.Model.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Reviews__UserID__5EBF139D");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.User", b =>
                {
                    b.HasOne("FullstackProject.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleID__4CA06362");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("FullstackProject.Model.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("FullstackProject.Model.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("FullstackProject.Model.Game", b =>
                {
                    b.Navigation("GameLibraries");

                    b.Navigation("Purchases");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FullstackProject.Model.Purchase", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FullstackProject.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FullstackProject.Model.User", b =>
                {
                    b.Navigation("GameLibraries");

                    b.Navigation("Membership");

                    b.Navigation("Purchases");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
