// <auto-generated />
using System;
using FullstackProject.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FullstackProject.Migrations
{
    [DbContext(typeof(S22024Group2ProjectContext))]
    partial class S22024Group2ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FullstackProject.Model.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CartId")
                        .HasName("PK__Cart__51BCD797A3AEE056");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("FullstackProject.Model.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .HasColumnType("int")
                        .HasColumnName("DeveloperID");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("DeveloperId")
                        .HasName("PK__Develope__DE084CD149B01792");

                    b.HasIndex(new[] { "Email" }, "UQ__Develope__A9D10534268086DC")
                        .IsUnique();

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("FullstackProject.Model.Game", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("int")
                        .HasColumnName("DeveloperID");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("GameId")
                        .HasName("PK__Games__2AB897DDDAE95024");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FullstackProject.Model.GameLibrary", b =>
                {
                    b.Property<int>("LibraryId")
                        .HasColumnType("int")
                        .HasColumnName("LibraryID");

                    b.Property<DateOnly?>("DateAdded")
                        .HasColumnType("date");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<decimal?>("PricePaid")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LibraryId")
                        .HasName("PK__GameLibr__A13647BF43F008E5");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("GameLibrary", (string)null);
                });

            modelBuilder.Entity("FullstackProject.Model.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .HasColumnType("int")
                        .HasColumnName("MembershipID");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MembershipId")
                        .HasName("PK__Membersh__92A785990BEA4EC2");

                    b.HasIndex(new[] { "UserId" }, "UQ__Membersh__1788CCADDB5B030F")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("FullstackProject.Model.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseID");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A5810BBE4EE");

                    b.HasIndex("PurchaseId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FullstackProject.Model.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseID");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<decimal?>("PricePaid")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PurchaseId")
                        .HasName("PK__Purchase__6B0A6BDE536E93D6");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("FullstackProject.Model.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79AEB172D10E");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FullstackProject.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A139672AF");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FullstackProject.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfileInfo")
                        .HasColumnType("text");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC0F3D84C5");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105349FA7B6FF")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FullstackProject.Model.Cart", b =>
                {
                    b.HasOne("FullstackProject.Model.Game", "Game")
                        .WithMany("Carts")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__Cart__GameID__693CA210");

                    b.HasOne("FullstackProject.Model.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Cart__UserID__68487DD7");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.Game", b =>
                {
                    b.HasOne("FullstackProject.Model.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .HasConstraintName("FK__Games__Developer__52593CB8");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("FullstackProject.Model.GameLibrary", b =>
                {
                    b.HasOne("FullstackProject.Model.Game", "Game")
                        .WithMany("GameLibraries")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__GameLibra__GameI__5629CD9C");

                    b.HasOne("FullstackProject.Model.User", "User")
                        .WithMany("GameLibraries")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__GameLibra__UserI__5535A963");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.Membership", b =>
                {
                    b.HasOne("FullstackProject.Model.User", "User")
                        .WithOne("Membership")
                        .HasForeignKey("FullstackProject.Model.Membership", "UserId")
                        .HasConstraintName("FK__Membershi__UserI__59FA5E80");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.Payment", b =>
                {
                    b.HasOne("FullstackProject.Model.Purchase", "Purchase")
                        .WithMany("Payments")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK__Payments__Purcha__656C112C");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("FullstackProject.Model.Purchase", b =>
                {
                    b.HasOne("FullstackProject.Model.Game", "Game")
                        .WithMany("Purchases")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__Purchases__GameI__628FA481");

                    b.HasOne("FullstackProject.Model.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Purchases__UserI__619B8048");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.Review", b =>
                {
                    b.HasOne("FullstackProject.Model.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__Reviews__GameID__5DCAEF64");

                    b.HasOne("FullstackProject.Model.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Reviews__UserID__5EBF139D");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullstackProject.Model.User", b =>
                {
                    b.HasOne("FullstackProject.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleID__4CA06362");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FullstackProject.Model.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("FullstackProject.Model.Game", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("GameLibraries");

                    b.Navigation("Purchases");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FullstackProject.Model.Purchase", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FullstackProject.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FullstackProject.Model.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("GameLibraries");

                    b.Navigation("Membership");

                    b.Navigation("Purchases");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
